import "@/app/globals.css";
import AuthProvider from "@/app/_providers/AuthProvider";
import ThemeRegistry from "@/lib/theme/ThemeRegistry";
import { ReactNode } from "react";
import { AppProviders } from "./_providers/AppProviders";
import ToastProvider from "./_providers/ToastProvider";

export const metadata = {
  title: "Food ordering app",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased">
        <ThemeRegistry>
          <AuthProvider>
            <AppProviders>
              {children}
              <ToastProvider />
            </AppProviders>
          </AuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
